server:
  port: 10831
logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:mysql://ch4njun-script-db.ckjufvaxbvyp.ap-northeast-2.rds.amazonaws.com:3306/cspm
    username: ch4njun
    password: cks14579
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql