server:
  port: 10831
logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:mysql://[IP]/cspm?createDatabaseIfNotExist=true
    username: [ID]
    password: [PW]
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
