server:
  port: 10831
logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/cspm
    username: root
    password: 1544
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql