server:
  port: 10831
logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:mysql://terraform-20210615050925589900000001.ckjufvaxbvyp.ap-northeast-2.rds.amazonaws.com/cspm?createDatabaseIfNotExist=true
    username: ch4njun
    password: cks14579!
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
