# Audit
AWS_ACCESS_KEY_ID = 'AKIAVUPQNSR77S3YDRUY'
AWS_SECRET_ACCESS_KEY = '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'

# Root
# AWS_ACCESS_KEY_ID = 'AKIAIR5FS76VR4HXOHDQ'
# AWS_SECRET_ACCESS_KEY = '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'

# Boss
# AWS_ACCESS_KEY_ID = 'AKIAY3O35BOOGRHTVA73'
# AWS_SECRET_ACCESS_KEY = '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'

AWS_DEFAULT_REGION = 'ap-northeast-2'